import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, CreditCard, Gem, Gift, HeartHandshake, PackageCheck, Plus } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/product-card";
import { categoryNames, formatPrice, media, products } from "@/lib/catalog";
export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Twinklingz by Priya Kaur | Premium Fashion Jewellery" },{ name: "description", content: "Discover elegant, contemporary fashion jewellery curated for every moment by Twinklingz." },{ property: "og:title", content: "Twinklingz by Priya Kaur" },{ property: "og:description", content: "Because every sparkle tells a story." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }),
  component: HomePage,
});
function HomePage() { return <main><CinematicHero/><CategorySection/><ProductsSection/><Campaign/><MostLoved/><ShopLook/><EditSection/><Story/><Why/><Social/><Newsletter/></main>; }
function CinematicHero() {
  const ref = useRef<HTMLElement>(null); const [progress, setProgress] = useState(0); const reduced = useReducedMotion();
  useEffect(() => { if (reduced) return; const onScroll = () => { const el = ref.current; if (!el) return; const rect = el.getBoundingClientRect(); setProgress(Math.min(1, Math.max(0, -rect.top / Math.max(1, el.offsetHeight - innerHeight)))); }; onScroll(); addEventListener("scroll", onScroll, { passive: true }); return () => removeEventListener("scroll", onScroll); }, [reduced]);
  const frame = Math.min(4, Math.floor(progress * 5)); const copy = ["TWINKLINGZ","Jewellery made for your moments.","Elegant.\nTimeless.\nUniquely You.","Because every sparkle tells a story.","TWINKLINGZ"];
  return <section ref={ref} className="relative h-[330vh] bg-primary"><div className="sticky top-0 h-screen overflow-hidden"><img src={media.heroImage} alt="Twinklingz jewellery worn with an ivory saree" width={1536} height={1024} className="absolute inset-0 h-full w-full object-cover" style={{ transform: `scale(${1 + progress * .06})` }}/><div className="absolute inset-0 bg-hero-shade"/><div className="absolute inset-0 flex items-center justify-center px-5 text-center text-primary-foreground"><motion.div key={frame} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className={`whitespace-pre-line font-display ${frame === 0 || frame === 4 ? "text-5xl sm:text-7xl lg:text-8xl" : "text-4xl sm:text-6xl"}`}>{copy[frame]}</p>{frame === 4 && <><p className="mt-3 font-script text-3xl text-champagne">by Priya Kaur</p><Button asChild size="lg" className="mt-8 bg-primary-foreground text-primary hover:bg-champagne"><Link to="/shop">EXPLORE THE COLLECTION <ArrowRight/></Link></Button></>}</motion.div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 text-center text-[10px] tracking-[0.3em] text-primary-foreground"><span>SCROLL TO DISCOVER</span><div className="mx-auto mt-3 h-12 w-px bg-primary-foreground/50"><div className="w-px bg-champagne" style={{ height: `${progress * 100}%` }}/></div></div></div></section>;
}
function Heading({ eyebrow, title, subtitle }: { eyebrow?: string; title: string; subtitle?: string }) { return <div className="mb-10 text-center">{eyebrow && <p className="mb-3 text-xs font-semibold tracking-[.24em] text-accent">{eyebrow}</p>}<h2 className="font-display text-4xl sm:text-5xl">{title}</h2>{subtitle && <p className="mx-auto mt-3 max-w-xl text-muted-foreground">{subtitle}</p>}</div>; }
function CategorySection() { return <section className="bg-background px-5 py-24 lg:px-10"><Heading eyebrow="DISCOVER" title="Shop by Category"/><div className="no-scrollbar mx-auto flex max-w-7xl snap-x gap-4 overflow-x-auto pb-4 lg:grid lg:grid-cols-6">{categoryNames.map((name, i) => <Link key={name} to={name === "New Arrivals" ? "/new-arrivals" : "/collections/$slug"} params={name === "New Arrivals" ? undefined : { slug: name.toLowerCase().replaceAll(" ", "-") }} className="group relative aspect-[3/4] min-w-[72vw] snap-start overflow-hidden sm:min-w-[40vw] lg:min-w-0"><img src={media.categoriesImage} alt={`${name} sample collection`} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" style={{ objectPosition: `${15 + i * 14}% center` }}/><div className="absolute inset-0 bg-card-shade"/><div className="absolute inset-x-0 bottom-0 p-5 text-primary-foreground"><h3 className="font-display text-2xl">{name}</h3><span className="mt-2 flex items-center gap-2 text-[10px] tracking-[.16em] opacity-0 transition group-hover:opacity-100">EXPLORE COLLECTION <ArrowRight className="size-3"/></span></div></Link>)}</div></section>; }
function ProductsSection() { return <section className="bg-secondary px-5 py-24 lg:px-10"><Heading eyebrow="NEW ARRIVALS" title="Just In ✦" subtitle="Fresh sparkle, made for your next moment."/><div className="mx-auto grid max-w-7xl grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-4 md:gap-6">{products.slice(0,4).map((p) => <ProductCard key={p.id} product={p}/>)}</div><div className="mt-12 text-center"><Button asChild variant="outline"><Link to="/new-arrivals">VIEW ALL NEW ARRIVALS <ArrowRight/></Link></Button></div></section>; }
function Campaign() { return <section className="relative min-h-[75vh] overflow-hidden"><img src={media.campaignImage} alt="Rose gold statement jewellery on burgundy velvet" width={1536} height={1024} loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-campaign-shade"/><div className="relative mx-auto flex min-h-[75vh] max-w-7xl items-center px-6 text-primary-foreground"><div className="max-w-lg"><p className="text-xs tracking-[.25em] text-champagne">THE OCCASION EDIT</p><h2 className="mt-4 font-display text-5xl sm:text-7xl">Made to be noticed.</h2><p className="mt-5 leading-7 text-primary-foreground/80">Discover jewellery that turns everyday moments into something extraordinary.</p><Button asChild className="mt-8 bg-primary-foreground text-primary"><Link to="/collections">SHOP THE EDIT</Link></Button></div></div></section>; }
function MostLoved() { return <section className="bg-background py-24"><Heading eyebrow="LOVED BY OUR CUSTOMERS" title="Most Loved"/><div className="no-scrollbar flex snap-x gap-5 overflow-x-auto px-5 lg:px-[max(2.5rem,calc((100vw-80rem)/2))]">{products.slice(1,7).map((p) => <div className="min-w-[72vw] snap-start sm:min-w-[40vw] lg:min-w-[280px]" key={p.id}><ProductCard product={p} showRating/></div>)}</div></section>; }
function ShopLook() { const [active,setActive]=useState(0); const hotspots = [{x:"28%",y:"25%",label:"Gul Drop Earrings",price:1499},{x:"43%",y:"47%",label:"Zarah Necklace",price:4299},{x:"42%",y:"79%",label:"Meher Bracelet",price:1899},{x:"30%",y:"82%",label:"Ruhi Ring",price:1299}]; return <section className="grid bg-secondary lg:grid-cols-[1.35fr_.65fr]"><div className="relative"><img src={media.lookImage} alt="Model wearing the Twinklingz occasion edit" width={1536} height={1024} loading="lazy" className="h-full min-h-[560px] w-full object-cover"/>{hotspots.map((h,i) => <button key={h.label} aria-label={`View ${h.label}`} onClick={() => setActive(i)} className="absolute flex size-8 items-center justify-center rounded-full border border-primary-foreground bg-primary/85 text-primary-foreground shadow-lg" style={{left:h.x,top:h.y}}><Plus className="size-4"/></button>)}</div><div className="flex items-center p-8 lg:p-14"><div><p className="text-xs tracking-[.24em] text-accent">SHOP THE LOOK</p><h2 className="mt-4 font-display text-5xl">The celebration edit</h2><p className="mt-5 text-muted-foreground">Tap the details to discover every piece in this curated look.</p><div className="mt-10 border-y border-border py-6"><p className="font-display text-2xl">{hotspots[active].label}</p><p className="mt-1">{formatPrice(hotspots[active].price)}</p><div className="mt-5 flex gap-3"><Button>ADD TO BAG</Button><Button asChild variant="outline"><Link to="/shop">VIEW PRODUCT</Link></Button></div></div></div></div></section>; }
function EditSection() { const edits=["Everyday Elegance","Date Night","Festive Sparkle","Statement Pieces","Minimal Muse","Gifting"]; return <section className="bg-background px-5 py-24 lg:px-10"><Heading eyebrow="CURATED FOR YOU" title="The Twinklingz Edit"/><div className="mx-auto grid max-w-7xl grid-cols-2 gap-3 md:grid-cols-4">{edits.map((e,i)=><Link to="/collections" key={e} className={`group relative overflow-hidden ${i===0||i===5 ? "col-span-2 row-span-2 aspect-[4/3]" : "aspect-square"}`}><img src={i%2?media.categoriesImage:media.campaignImage} alt={`${e} sample edit`} loading="lazy" width={1536} height={1024} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-card-shade"/><h3 className="absolute bottom-5 left-5 font-display text-2xl text-primary-foreground sm:text-3xl">{e}</h3></Link>)}</div></section>; }
function Story(){return <section className="grid bg-blush lg:grid-cols-2"><img src={media.heroImage} alt="Twinklingz brand story" width={1536} height={1024} loading="lazy" className="h-full min-h-[480px] w-full object-cover"/><div className="flex items-center px-6 py-20 lg:px-20"><div className="max-w-xl"><p className="text-xs tracking-[.25em] text-accent">ABOUT TWINKLINGZ</p><h2 className="mt-4 font-display text-5xl">Jewellery for the stories only you can tell.</h2><p className="mt-6 leading-8 text-muted-foreground">We bring you elegant, timeless, and trend-forward jewellery designed to complement every style and occasion. From everyday essentials to statement pieces, each collection is carefully curated to help you shine with confidence.</p><p className="mt-7 font-script text-3xl text-primary">Because every sparkle tells a story. ✦</p><Button asChild variant="outline" className="mt-8"><Link to="/about">OUR STORY</Link></Button></div></div></section>}
function Why(){const items=[[Gem,"Premium Designs"],[HeartHandshake,"Carefully Curated"],[CreditCard,"Secure Payments"],[PackageCheck,"Quality Focused"],[Gift,"Thoughtful Packaging"]] as const;return <section className="bg-background px-5 py-20"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-10 text-center md:grid-cols-5">{items.map(([Icon,label])=><div key={label}><Icon className="mx-auto size-7 stroke-1 text-accent"/><p className="mt-4 font-display text-lg">{label}</p></div>)}</div></section>}
function Social(){return <section className="bg-secondary px-5 py-24"><Heading eyebrow="WEAR IT · STYLE IT · MAKE IT YOURS" title="@Twinklingz"/><div className="mx-auto grid max-w-6xl grid-cols-2 gap-2 md:grid-cols-4">{[media.heroImage,media.categoriesImage,media.lookImage,media.campaignImage].map((src,i)=><img key={src} src={src} alt={`Twinklingz style inspiration ${i+1}`} width={600} height={600} loading="lazy" className="aspect-square w-full object-cover"/>)}</div><div className="mt-8 text-center"><Button variant="outline">FOLLOW OUR JOURNEY</Button></div></section>}
function Newsletter(){return <section className="bg-primary px-5 py-20 text-center text-primary-foreground"><p className="font-script text-2xl text-champagne">An invitation to sparkle</p><h2 className="mt-3 font-display text-5xl">Join the Twinklingz Circle</h2><p className="mx-auto mt-4 max-w-xl text-primary-foreground/70">Be the first to discover new drops, exclusive collections and special offers.</p><form className="mx-auto mt-8 flex max-w-xl border-b border-primary-foreground/50" onSubmit={(e)=>e.preventDefault()}><input type="email" required placeholder="Your email address" className="w-full bg-transparent px-2 py-4 outline-none placeholder:text-primary-foreground/50"/><Button type="submit" variant="ghost" className="text-primary-foreground">JOIN NOW <ArrowRight/></Button></form></section>}
