import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ListFilter, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { ProductCard } from "@/components/product-card";
import { products } from "@/lib/catalog";
export const Route = createFileRoute("/shop")({ head: () => ({ meta: [{title:"Shop All Jewellery | Twinklingz"},{name:"description",content:"Shop premium fashion necklaces, earrings, bracelets, rings and jewellery sets."},{property:"og:title",content:"Shop All Jewellery | Twinklingz"},{property:"og:description",content:"Discover the complete Twinklingz jewellery collection."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: ShopPage });
const groups=["Category","Price","Availability","Colour","Material","Plating","Stone","Occasion","Collection","New Arrivals","Bestsellers"];
function Filters(){return <div>{groups.map((g)=><details key={g} className="border-b border-border py-4"><summary className="cursor-pointer text-xs font-semibold tracking-widest">{g.toUpperCase()}</summary><div className="mt-3 space-y-2 text-sm text-muted-foreground">{["All","Featured","In stock"].map(x=><label key={x} className="flex items-center gap-2"><input type="checkbox"/> {x}</label>)}</div></details>)}</div>}
function ShopPage(){const [sort,setSort]=useState("featured");return <main className="min-h-screen bg-background px-5 pb-24 pt-36 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between border-b border-border pb-8"><div><p className="text-xs tracking-[.2em] text-accent">DISCOVER</p><h1 className="mt-2 font-display text-5xl">Shop All</h1><p className="mt-2 text-sm text-muted-foreground">{products.length} styles</p></div><div className="flex gap-3"><Sheet><SheetTrigger asChild><Button variant="outline" className="lg:hidden"><ListFilter/> FILTER</Button></SheetTrigger><SheetContent side="bottom" className="max-h-[85vh] overflow-auto bg-background"><SheetHeader><SheetTitle>Filter jewellery</SheetTitle></SheetHeader><Filters/></SheetContent></Sheet><select value={sort} onChange={(e)=>setSort(e.target.value)} className="border border-input bg-background px-3 text-sm"><option value="featured">Featured</option><option value="new">Newest</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="best">Bestselling</option></select></div></div><div className="mt-6 flex items-center gap-2"><span className="border border-border px-3 py-2 text-xs">In stock <X className="ml-2 inline size-3"/></span><Button variant="link" className="text-xs">Clear All</Button></div><div className="mt-8 grid gap-8 lg:grid-cols-[240px_1fr]"><aside className="hidden lg:block"><Filters/></aside><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></div></main>}
